[mgr]
prepend_keymap = [
    { on = [
        "f",
        "g",
    ], run = "plugin fg", desc = "find file by content (fuzzy match)" },
    { on = [
        "f",
        "G",
    ], run = "plugin fg --args='rg'", desc = "find file by content (ripgrep match)" },
    { on = [
        "f",
        "f",
    ], run = "plugin fg --args='fzf'", desc = "find file by filename" },
]
