{
  config,
  lib,
  pkgs,
  ...
}: let
  port = config.yomi.ports.anonaddy;
  dataDir = "/persist/data/anonaddy";
  configDir = "/persist/state/anonaddy";
in {
  yomi.nginx.at.alias.port = port;

  sops.secrets.anonaddy_env = {
    sopsFile = ../secrets.yaml;
    owner = "root";
    group = "root";
    mode = "0400";
  };

  systemd.tmpfiles.rules = [
    "d ${dataDir} 0755 root root"
    "d ${configDir} 0755 root root"
  ];
  virtualisation.oci-containers.containers."addy" = {
    image = "anonaddy/anonaddy:latest";
    environmentFiles = [
      config.sops.secrets.anonaddy_env.path
    ];
    environment = {
      "ANONADDY_DOMAIN" = "yokai.hugo-berendi.de";
      "ANONADDY_HOSTNAME" = config.yomi.nginx.at.alias.host;
      "ANONADDY_DNS_RESOLVER" = "127.0.0.1";

      "APP_DEBUG" = "false";
      "APP_URL" = config.yomi.nginx.at.alias.url;

      "REDIS_HOST" = "valkey";
      "REAL_IP_FROM" = "0.0.0.0/32";
      "REAL_IP_HEADER" = "X-Forwarded-For";
      "ANONADDY_ADDITIONAL_USERNAME_LIMIT" = "3";
      "ANONADDY_BANDWIDTH_LIMIT" = "104857600";
      "ANONADDY_LIMIT" = "200";
      "ANONADDY_NEW_ALIAS_LIMIT" = "100";
      "LOG_IP_VAR" = "remote_addr";
      "OPCACHE_MEM_SIZE" = "128";
      "POSTFIX_DEBUG" = "false";

      "POSTFIX_RELAYHOST" = "smtp.migadu.com:465";
      "POSTFIX_RELAYHOST_AUTH_ENABLE" = "true";
      "POSTFIX_SMTP_TLS" = "encrypt";
    };
    volumes = [
      "${dataDir}:/data:rw"
    ];
    ports = [
      "25:25/tcp"
      "${toString port}:8000/tcp"
    ];
    dependsOn = [
      "addy_db"
      "addy_valkey"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=addy"
      "--network=addy_default"
    ];
  };
  systemd.services."docker-addy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-addy_default.service"
    ];
    requires = [
      "docker-network-addy_default.service"
    ];
    partOf = [
      "docker-compose-addy-root.target"
    ];
    wantedBy = [
      "docker-compose-addy-root.target"
    ];
  };
  virtualisation.oci-containers.containers."addy_db" = {
    image = "mariadb:10";
    environmentFiles = [
      config.sops.secrets.anonaddy_env.path
    ];
    environment = {
      "MARIADB_RANDOM_ROOT_PASSWORD" = "yes";
      "MARIADB_DATABASE" = "anonaddy";
      "MARIADB_USER" = "anonaddy";
    };
    volumes = [
      "${configDir}/mysql:/var/lib/mysql:rw"
    ];
    cmd = ["mysqld" "--character-set-server=utf8mb4" "--collation-server=utf8mb4_unicode_ci"];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=addy_default"
    ];
  };
  systemd.services."docker-addy_db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-addy_default.service"
    ];
    requires = [
      "docker-network-addy_default.service"
    ];
    partOf = [
      "docker-compose-addy-root.target"
    ];
    wantedBy = [
      "docker-compose-addy-root.target"
    ];
  };
  virtualisation.oci-containers.containers."addy_valkey" = {
    image = "valkey/valkey:alpine";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=valkey"
      "--network=addy_default"
    ];
  };
  systemd.services."docker-addy_valkey" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-addy_default.service"
    ];
    requires = [
      "docker-network-addy_default.service"
    ];
    partOf = [
      "docker-compose-addy-root.target"
    ];
    wantedBy = [
      "docker-compose-addy-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-addy_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f addy_default";
    };
    script = ''
      docker network inspect addy_default || docker network create addy_default
    '';
    partOf = ["docker-compose-addy-root.target"];
    wantedBy = ["docker-compose-addy-root.target"];
  };

  systemd.targets."docker-compose-addy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
