{
  config,
  lib,
  pkgs,
  ...
}: let
  dataDir = "/persist/data/pelican";
  logsDir = "/persist/state/pelican/logs";
in {
  yomi.cloudflared.at.pelican.port = config.yomi.ports.pelican-panel;

  # TODO: narrow these once the panel image's runtime uid is known; 0777 is a
  # stand-in for not knowing which user inside the container writes here.
  systemd.tmpfiles.rules = [
    "d ${dataDir} 0777 root root"
    "d ${logsDir} 0777 root root"
    "d ${logsDir}/supervisord 0777 root root"
  ];

  virtualisation.oci-containers.containers."pelican-panel" = {
    # Panel and wings use separate version numbers but ship in pairs on the
    # same day; beta38 is the counterpart to wings v1.0.0-beta29. The images
    # moved to ghcr.io/pelican -- the old pelican-dev path no longer serves
    # even a pull token, so the previously pinned beta25 had become
    # unfetchable too.
    image = "ghcr.io/pelican/panel:v1.0.0-beta38";
    environment = {
      "ADMIN_EMAIL" = "pelican@hugo-berendi.de";
      "APP_URL" = config.yomi.cloudflared.at.pelican.url;
      "XDG_DATA_HOME" = "/pelican-data";

      # TLS is terminated by the cloudflare tunnel. Without this the entrypoint
      # refuses to start an https APP_URL, asking for a Let's Encrypt address
      # it must not need. The address is this network's gateway, matching the
      # trusted_proxies entry in ./Caddyfile.
      "TRUSTED_PROXIES" = "172.20.0.1";
    };
    volumes = [
      "${dataDir}:/pelican-data:rw"
      "${logsDir}:/var/www/html/storage/logs:rw"
      "${toString ./Caddyfile}:/etc/caddy/Caddyfile"
    ];
    ports = [
      "${toString config.yomi.cloudflared.at.pelican.port}:80"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=panel"
      "--network=pelican_default"
    ];
  };
  systemd.services."docker-pelican-panel" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-pelican_default.service"
    ];
    requires = [
      "docker-network-pelican_default.service"
    ];
    partOf = [
      "docker-compose-pelican-root.target"
    ];
    wantedBy = [
      "docker-compose-pelican-root.target"
    ];
  };

  systemd.services."docker-network-pelican_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f pelican_default";
    };
    script = ''
      # Subnets in use on this host: 172.17 docker0, 172.18 changedetection,
      # 172.19 affine, 172.21 pelican_nw. Creating this network on 172.19
      # failed with "Pool overlaps with other one on this address space".
      docker network inspect pelican_default || docker network create pelican_default --subnet=172.20.0.0/16
    '';
    partOf = ["docker-compose-pelican-root.target"];
    wantedBy = ["docker-compose-pelican-root.target"];
  };

  systemd.targets."docker-compose-pelican-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
