#!/usr/bin/env bash

iDIR="$HOME/dotfiles/yomi/home/features/desktop/dunst/icons"

# Get brightness
get_backlight() {
    max=$(brightnessctl m)
    current=$(brightnessctl g)
	LIGHT=$(awk "BEGIN {printf \"%.0f\n\", $current / $max * 100}")
	echo "${LIGHT}"
}

# Get icons
get_icon() {
	current="$(get_backlight)"
	if [[ "$current" -le 20 ]]; then
		echo "$iDIR/brightness-20.png"
	elif [[ "$current" -le 40 ]]; then
		echo "$iDIR/brightness-40.png"
	elif [[ "$current" -le 60 ]]; then
		echo "$iDIR/brightness-60.png"
	elif [[ "$current" -le 80 ]]; then
		echo "$iDIR/brightness-80.png"
	else
		echo "$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	local brightness=$(get_backlight)
	notify-send -u low -i "$(get_icon)" "Brightness: $brightness%" -h int:value:"$brightness"
}

# Increase brightness
inc_backlight() {
	brightnessctl s +5% && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl s 5%- && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
